eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
 ---            
 server:
   port: 18081
 spring:
    profiles: user
    application:
      name: springcloud-config-user
